/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c0c8cc',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f3f0eb',
        'on-secondary-fixed-variant': '#324e2a',
        'on-secondary-container': '#4f6c45',
        'on-primary-container': '#9cd7ef',
        'surface-dim': '#dcdad5',
        'on-primary-fixed': '#001f29',
        'on-surface': '#1c1c19',
        'secondary-fixed': '#caecbc',
        background: '#f9f6f2',
        outline: '#70787c',
        'on-error-container': '#93000a',
        'surface-container-low': '#f6f3ee',
        'on-secondary': '#ffffff',
        'surface-container-high': '#ebe8e3',
        tertiary: '#5f3705',
        'surface-container-highest': '#e5e2dd',
        secondary: '#496640',
        'tertiary-fixed-dim': '#f7bb7e',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e5e2dd',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdcbd',
        'surface-tint': '#27667b',
        'primary-fixed-dim': '#94cfe7',
        'on-tertiary-fixed-variant': '#663d0b',
        'on-background': '#1c1c19',
        'tertiary-container': '#7a4e1c',
        'surface-container': '#f0ede8',
        'on-secondary-fixed': '#062104',
        'primary-container': '#1e5f74',
        'error-container': '#ffdad6',
        surface: '#f9f6f2',
        'inverse-surface': '#31302d',
        'secondary-container': '#caecbc',
        'on-surface-variant': '#40484c',
        'surface-bright': '#f9f6f2',
        'on-tertiary-fixed': '#2c1600',
        'inverse-primary': '#94cfe7',
        'secondary-fixed-dim': '#afd0a1',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffc286',
        error: '#ba1a1a',
        'primary-fixed': '#b9eaff',
        primary: '#0a4d52',
        'on-primary-fixed-variant': '#004d62',
      },
      boxShadow: {
        soft: '0 4px 24px rgba(28, 28, 25, 0.06)',
        card: '0 18px 50px -18px rgba(10, 77, 82, 0.14)',
        'card-hover': '0 26px 64px -18px rgba(10, 77, 82, 0.2)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
